set encoding=utf-8
call plug#begin()
Plug 'tpope/vim-fugitive'
Plug 'arcticicestudio/nord-vim'
Plug 'rhysd/vim-grammarous'
Plug 'habamax/vim-rst'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf'
Plug 'jayli/vim-easycomplete'
Plug 'chase/vim-ansible-yaml'
Plug 'Sirver/ultisnips'
Plug 'pearofducks/ansible-vim', { 'do': './UltiSnips/generate.sh' }
Plug 'honza/vim-snippets'
Plug 'Yggdroot/indentLine'
call plug#end()

" highlight
syntax enable
set hlsearch

" indentation rules
let g:indentLine_char = '⦙'
set tabstop=4
set shiftwidth=2
set expandtab
set autoindent
autocmd FileType yaml set tabstop=2 shiftwidth=2

" persistent undo
set undodir=~/.vim/undodir
set undofile

" easy complete settings
let g:easycomplete_tab_trigger="<c-space>"

" theme
set number
set showmatch
set laststatus=2
set noshowmode
set cursorline
set t_Co=256
set termguicolors
let g:nord_cursor_line_number_background = 1
let g:nord_uniform_status_lines = 1
let g:nord_bold_vertical_split_line = 1
let g:nord_italic_comments = 1
let g:nord_italic_comments = 1
