" language and encoding
set encoding=utf-8
language en_US.UTF-8

" plugin manager
" git clone https://github.com/kristijanhusak/vim-packager ~/.vim/pack/packager/opt/vim-packager

function! s:packager_init(packager) abort
  call a:packager.add('kristijanhusak/vim-packager', { 'type': 'opt' })
  call a:packager.add('k-takata/minpac', {'type': 'opt'})
  call a:packager.add('tpope/vim-fugitive')
  call a:packager.add('preservim/nerdtree')
  call a:packager.add('vim-syntastic/syntastic')
  call a:packager.add('rhysd/vim-grammarous')
  call a:packager.add('habamax/vim-rst')
  call a:packager.add('arcticicestudio/nord-vim')
  call a:packager.add('Sirver/ultisnips')
  call a:packager.add('ckunte/latex-snippets-vim')
  call a:packager.add('Yggdroot/indentLine')
  call a:packager.add('rhysd/vim-grammarous')
  call a:packager.add('jayli/vim-easycomplete')
  call a:packager.add('pearofducks/ansible-vim')
  call a:packager.add('chase/vim-ansible-yaml', { 'do': './UltiSnips/generate.sh' })
  call a:packager.add('arcticicestudio/nord-vim')
  call a:packager.add('itchyny/lightline.vim')
endfunction  

packadd vim-packager
call packager#setup(function('s:packager_init'))

" highlight
syntax enable
set hlsearch

" wrap
set wrap linebreak nolist
set textwidth=79
set formatoptions+=l
set whichwrap+=<,>,h,l

" indentation rules
let g:indentLine_char = '⦙'
set tabstop=4
set shiftwidth=2
set expandtab
set autoindent
autocmd FileType yaml set tabstop=2 shiftwidth=2

" persistent undo
set undodir=~/.vim/undodir
set undofile

" easy complete settings
let g:easycomplete_tab_trigger="<c-space>"

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" look and feel
set number
set showmatch
set laststatus=2
set noshowmode
set cursorline
set t_Co=256
set termguicolors
let g:nord_cursor_line_number_background = 1
let g:nord_uniform_status_lines = 1
let g:nord_bold_vertical_split_line = 1
let g:nord_italic_comments = 1
let g:nord_italic_comments = 1
hi Visual term=reverse cterm=reverse guibg=Grey
