# antibody
# curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
source <(antibody init)

# autocomplete stuff
autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi
zmodload -i zsh/complist
setopt auto_cd
setopt correct_all
setopt auto_list
setopt auto_menu
setopt always_to_end
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:::::' completer _expand _complete _ignored _approximate

# zsh history
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups 
setopt hist_reduce_blanks 
setopt inc_append_history 
setopt share_history 

# plugins
antibody bundle zdharma/fast-syntax-highlighting
antibody bundle zsh-users/zsh-autosuggestions
antibody bundle zsh-users/zsh-completions
antibody bundle denysdovhan/spaceship-prompt
antibody bundle peterhurford/git-aliases.zsh

# spaceship
spaceship_vi_mode_enable
SPACESHIP_EXEC_TIME_SHOW=false
SPACESHIP_VI_MODE_COLOR=blue

# alias
alias ll='ls -alh'
alias man='pinfo -m'
