#Plugins 
source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt

# Path 
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# Auto Complete
autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
    compinit -i
  else
      compinit -C -i
fi
zmodload -i zsh/complist

# History 
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history

# Auto Correct & Friends
setopt correct_all
setopt auto_list
setopt auto_menu
setopt always_to_end
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:::::' completer _expand _complete _ignored _approximate

# Spaceship
SPACESHIP_PROMPT_ORDER=(
    user          
    dir    
    host   
    git   
    line_sep
    vi_mode 
    jobs    
    exit_code
    char    
    )
    SPACESHIP_PROMPT_ADD_NEWLINE=false
    SPACESHIP_CHAR_SYMBOL="❯"
    SPACESHIP_CHAR_SUFFIX=" "

# aliases
alias ll="ls -lah"
alias la="ls -a"
alias l="ls -lh"
alias cat=bat

# alias plugin
export PRINT_ALIAS_PREFIX='  ╰─> '
export PRINT_ALIAS_FORMAT=$'\e[1m'
export PRINT_NON_ALIAS_FORMAT=$'\e[0m'
export PRINT_ALIAS_IGNORE_REDEFINED_COMMANDS=true
export PRINT_ALIAS_IGNORE_ALIASES=(my_alias my_other_alias)

